### PR TITLE
seaparate functions and test them

### PR DESCRIPTION
**Pull request by kwadrat**
A couple of functions was moved to global scope so that they could be tested

### CODE REVIEW

**Comment by djmitche** [comment]
Looks good.  Just a PEP8 issue to clean up (as detected by travis).

**Comment by kwadrat** [comment]
OK, I applied PEP8.

**Comment by kwadrat** [comment]
Thank you for the merging! I think I will give up the work on IPv6 support - it's too much for a couple of hours and PyCon in Montreal soon is over. Thank you for your guidance!

**Comment by djmitche** [comment]
Absolutely -- thank you for your contributions!

**Pull request merged**
